- hosts: 
  - cdh-cluster
  roles: 
  - common
  tags: "common"
  
- hosts: 
  - cdh-cluster
  roles: 
  - jdk
  tags: "jdk"
  
- hosts: 
  - cdh-server
  roles: 
  - ssh
  tags: "ssh"

- hosts: 
  - cdh-agent
  roles: 
  - ssh
  tags: "ssh"
  
- hosts: 
  - cdh-cluster
  roles: 
  - cm
  tags: "cm"

- hosts: 
  - cdh-server
  roles: 
  - cdh
  tags: "cdh"