- hosts: 
  - cdh-cluster
  roles: 
  - common
  tags: "common"
  
- hosts: 
  - cdh-cluster
  roles: 
  - jdk
  tags: "jdk"
  
- hosts: 
  - cdh-cluster
  roles: 
  - cm
  tags: "cm"
  
# - hosts: 
#   - cdh-master
#   roles: 
#   - ca
# 
# - hosts: 
#   - cdh-workers
#   roles: 
#   - ca
# 
- hosts: 
  - cdh-server
  roles: 
  - cdh
  tags: "cdh"