- name: 下载 cm yum 仓库
  # debug: msg={{ groups['cdh-server'] }}
  get_url: url={{ v_yum_repo_url }} dest=/etc/yum.repos.d/
  
- name: 导入仓库签名 GPG 密钥
  shell: "rpm --import {{ v_yum_repo_gpgcheck_url }}"

- name: 安装 cloudera-manager-daemons cloudera-manager-agent
  yum: update_cache=yes name={{ item }} state=present
  with_items:
  - cloudera-manager-daemons
  - cloudera-manager-agent

- name: 安装 cloudera-manager-server
  yum: update_cache=yes name={{ item }} state=present
  with_items:
  - cloudera-manager-server
  when: "'cdh-server' in group_names"

- name: 拷贝 cm 配置文件
  template: src={{ item }} dest=/etc/cloudera-scm-agent/config.ini mode=644
  with_items:
  - config.ini

- name: 重启 cloudera-scm-agent 服务，并设置自启动
  systemd:
    name: cloudera-scm-agent
    daemon_reload: yes
    state: restarted
    enabled: yes

- name: 初始化数据库
  shell: "/opt/cloudera/cm/schema/scm_prepare_database.sh mysql -h {{ v_cm_db_host }} -P {{ v_cm_db_port }} --scm-host {{ v_server_ip }} {{ v_cm_db_name }} {{ v_cm_db_user }} {{ v_cm_db_password }} "
  when: "'cdh-server' in group_names"
