- name: 准备 kylin 工作目录
  file: name={{ item }} state=directory owner={{ hadoop_user }} group={{ hadoop_group }} mode=0755
  with_items:
  - "{{ kylin_work_path }}"
  
- name: 下载 kylin 安装包
  get_url: url={{ kylin_download_url }} dest=/tmp owner={{ hadoop_user }} group={{ hadoop_group }} mode=644

- name: 解压 kylin 安装包
  unarchive:
    # src也可以直接填写一个URL地址直接进行下载解压
    src: "/tmp/apache-kylin-{{kylin_version}}-bin-{{kylin_env}}.tar.gz"
    copy: no
    dest: "{{ kylin_work_path }}"
    owner: "{{ hadoop_user }}"
    group: "{{ hadoop_group }}"
    
- name: 调整 kylin 目录所有者
  file: name={{ kylin_path }} state=directory recurse=yes owner={{ hadoop_user }} group={{ hadoop_group }} 

- name: 设置 kylin 环境变量
  template: src=kylin_env.sh dest=/etc/profile.d

- name: 生效 kylin 环境变量
  shell: "source /etc/profile.d/kylin_env.sh"
