- name: 准备 HBase 工作目录
  file: name={{ item }} state=directory owner={{ hadoop_user }} group={{ hadoop_group }} mode=0755
  with_items:
  - "{{ hbase_work_path }}"
  - "{{ hbase_log_path }}"
  - "{{ hbase_tmp_path }}"
  
- name: 下载 hbase 安装包
  get_url: url={{ hbase_download_url }} dest=/tmp owner={{ hadoop_user }} group={{ hadoop_group }} mode=644

- name: 解压 hbase 安装包
  unarchive:
    # src也可以直接填写一个URL地址直接进行下载解压
    src: "/tmp/hbase-{{ hbase_version }}-bin.tar.gz"
    copy: no
    dest: "{{ hbase_work_path }}"
    owner: "{{ hadoop_user }}"
    group: "{{ hadoop_group }}"
    
- name: 调整 hbase 目录所有者
  file: name={{ hbase_path }} state=directory recurse=yes owner={{ hadoop_user }} group={{ hadoop_group }} 

- name: 设置 hbase 环境变量
  template: src=hbase_env.sh dest=/etc/profile.d

- name: 生效 hbase 环境变量
  shell: "source /etc/profile.d/hbase_env.sh"

- name: 拷贝 hbase 配置文件
  template: src={{ item }} dest={{ hbase_config_path }} owner={{ hadoop_user }} group={{ hadoop_group }} mode=644
  with_items:
  - hbase-site.xml
  - hbase-env.sh
  - regionservers



