- name: 下载 cdh Parcels
  get_url: url={{ item }} dest=/opt/cloudera/parcel-repo owner=cloudera-scm group=cloudera-scm mode=644
  with_items:
  - "{{ v_cdh_manifest_download_url }}"
  - "{{ v_cdh_download_url }}"

- name: 下载 cdh parcel.sha256 并改名为 parcel.sha
  get_url: url={{ item }} dest="/opt/cloudera/parcel-repo/CDH-{{v_cdh_version}}-1.cdh{{v_cdh_version}}.p{{v_cdh_version_p}}-el7.parcel.sha" owner=cloudera-scm group=cloudera-scm mode=644
  with_items:
  - "{{ v_cdh_sha_download_url }}"

- name: 将 manifest.json 文件中，找到对应版本的秘钥，复制到 .sha 文件中
  shell: 'echo "2e650f1f1ea020a3efc98a231b85c2df1a50b030" > "/opt/cloudera/parcel-repo/CDH-{{v_cdh_version}}-1.cdh{{v_cdh_version}}.p{{v_cdh_version_p}}-el7.parcel.sha"'

- name: 重启 cloudera-scm-server 服务，并设置自启动
  systemd:
    name: cloudera-scm-server
    daemon_reload: yes
    state: restarted
    enabled: yes
