# - name: 准备工作目录
#   file: name={{ item }} state=directory owner={{ cdh_user }} group={{ cdh_group }} mode=0755
#   with_items:
#   - "{{ cm_work_path }}"
#   - "/var/lib/cloudera-scm-server"
#   - "/opt/cloudera/parcel-repo"
#   - "{{ cdh_path_jobtracker }}"
#   - "{{ cdh_path_tasktracker }}"
# 
 
# - name: 解压 cm 安装包
#   unarchive:
#     # src也可以直接填写一个URL地址直接进行下载解压
#     src: "/tmp/cloudera-manager-centos7-cm{{cm_version}}_x86_64.tar.gz"
#     copy: no
#     dest: "{{ cm_work_path }}"
#     owner: "{{ cdh_user }}"
#     group: "{{ cdh_group }}"
# 
# - name: 调整 cm 目录所有者
#   file: name={{ cm_path }} state=directory recurse=yes owner={{ cdh_user }} group={{ cdh_group }}
# 
# - name: 拷贝 cm 配置文件
#   template: src={{ item }} dest={{ cm_path }}/etc/cloudera-scm-agent/ owner={{ cdh_user }} group={{ cdh_group }} mode=644
#   with_items:
#   - config.ini
# 
# - name: 添加 cloudera-scm 用户 
#   user:
#     name: cloudera-scm
#     append: yes
#     createhome: no
#     system: yes
#     home: "{{ cm_path }}/run/cloudera-scm-server"
#     shell: /bin/false
#     comment: "Cloudera SCM User"
# 
# - name: 拷贝 mysql-connector 包
#   copy: src=mysql-connector-java-5.1.46.jar dest={{ cm_path }}/share/cmf/lib mode=644
# 
# - name: 初始化数据库
#   shell: "{{ cm_path }}/share/cmf/schema/scm_prepare_database.sh {{cm_db_type}} {{cm_db_name}} -h{{cm_db_host}} -u{{cm_db_user}} -p'{{cm_db_password}}' -P{{cm_db_port}} --scm-host {{cdh_master_ip}} scm scm scm"
#   ignore_errors: true
#   run_once: true
# 
# - name: 下载 cdh Parcels
#   get_url: url={{ item }} dest=/opt/cloudera/parcel-repo owner=cloudera-scm group=cloudera-scm mode=644
#   with_items:
#   - "{{ v_cdh_manifest_download_url }}"
#   - "{{ v_cdh_download_url }}"
# 
# - name: 下载 cdh parcel.sha256 并改名为 parcel.sha
#   get_url: url={{ item }} dest="/opt/cloudera/parcel-repo/CDH-{{v_cdh_version}}-1.cdh{{v_cdh_version}}.p{{v_cdh_version_p}}-el7.parcel.sha" owner=cloudera-scm group=cloudera-scm mode=644
#   with_items:
#   - "{{ v_cdh_sha_download_url }}"
# 
# - name: 将 manifest.json 文件中，找到对应版本的秘钥，复制到 .sha 文件中
#   shell: 'echo "2e650f1f1ea020a3efc98a231b85c2df1a50b030" > "/opt/cloudera/parcel-repo/CDH-{{v_cdh_version}}-1.cdh{{v_cdh_version}}.p{{v_cdh_version_p}}-el7.parcel.sha"'

- name: 重启 cloudera-scm-server 服务，并设置自启动
  systemd:
    name: cloudera-scm-server
    daemon_reload: yes
    state: restarted
    enabled: yes
# 
# - name: 设置 cdh 环境变量
#   template: src=cdh_env.sh dest=/etc/profile.d
# 
# - name: 生效 cdh 环境变量
#   shell: "source /etc/profile.d/cdh_env.sh"
