- name: 准备 sqoop 工作目录
  file: name={{ item }} state=directory owner={{ sqoop_user }} group={{ sqoop_group }} mode=0755
  with_items:
  - "{{ sqoop_work_path }}"

- name: 下载 sqoop 安装包
  get_url: url={{ sqoop_download_url }} dest=/tmp owner={{ sqoop_user }} group={{ sqoop_group }} mode=644

- name: 解压 sqoop 安装包
  unarchive:
    src: "/tmp/sqoop-{{sqoop_version}}.bin__hadoop-{{sqoop_hadoop_version}}.tar.gz"
    copy: no
    dest: "{{ sqoop_work_path }}"
    owner: "{{ sqoop_user }}"
    group: "{{ sqoop_group }}"

- name: 调整 sqoop 目录所有者
  file: name={{ sqoop_path }} state=directory recurse=yes owner={{ sqoop_user }} group={{ sqoop_group }} 

- name: 设置 sqoop 环境变量
  template: src=sqoop_env.sh dest=/etc/profile.d

- name: 生效 sqoop 环境变量
  shell: "source /etc/profile.d/sqoop_env.sh"

- name: 拷贝 mysql-connector 包
  copy: src=../jdk/files/mysql-connector-java-5.1.46.jar dest={{ sqoop_path }}/lib mode=644


