# - name: 卸载系统自带 JDK
#   yum: name={{ item }} state=absent
#   with_items: 
#   - "java*"
#   - "jdk*"
#   - "oracle-j2sdk*"
#   when: v_jdk_install=="true"
  
# - name: 下载 JDK
#   get_url: url={{ item }} dest=/tmp mode=644
#   with_items:
#   - "{{ v_cdh_oracle_j2sdk_download_url }}"
#   when: v_jdk_install=="true"

- name: 安装 JDK
  yum: name={{ item }} state=present
  with_items: 
  - "/tmp/oracle-j2sdk1.8-1.8.0+update141-1.x86_64.rpm"
  when: v_jdk_install=="true"

- name: 配置 JAVA_HOME
  template: src=cdh_java_home.sh dest=/etc/profile.d
  when: v_jdk_install=="true"

- name: 生效 JAVA_HOME
  shell: "source /etc/profile.d/cdh_java_home.sh"
  when: v_jdk_install=="true"

- name: 准备 java 共享目录
  file: name={{ item }} state=directory mode=0755
  with_items:
  - "/usr/share/java"

- name: 拷贝 mysql-connector 包
  copy: src=mysql-connector-java-5.1.46.jar dest=/usr/share/java/mysql-connector-java.jar mode=644
